Movie.create!([
  {title: "The Black Rose of England", year: 1937, plot: "Velit enim est et doloremque consequuntur tempora voluptates qui. Soluta quis rerum ut quos officia et nostrum praesentium. Quos praesentium doloribus qui deserunt.", director: "Dominque Bins", english: true},
  {title: "Christmas on Latoyia Passage", year: 1987, plot: "Deserunt maxime aperiam error rerum ut. Assumenda itaque blanditiis et ipsa sequi. Ad voluptate itaque voluptatum neque. Maiores unde maxime optio consequatur sit velit labore. Et temporibus autem fugit odit omnis cum.", director: "Corrina Wolf", english: true},
  {title: "Blonde Clash", year: 2008, plot: "Qui aut alias aut voluptatibus fugiat consectetur ut. Placeat officia veritatis fugit vel voluptatum. Sapiente sit rerum illo id. Aut tenetur dolores ut facilis illo incidunt odit occaecati. Eligendi modi provident perferendis id.", director: "Desiree Bauch", english: true},
  {title: "317 A.D.", year: 1959, plot: "Aut eos assumenda sed amet. Commodi in sit aut cupiditate. Non velit sint aut odit reiciendis perferendis quasi aliquid.", director: "Jorge Walsh", english: true},
  {title: "When Pura Met Moshe", year: 1976, plot: "Est accusamus voluptatem saepe dolores deserunt. Molestiae sit sapiente voluptas dignissimos vitae et natus. Qui rerum ipsam sed eveniet sapiente ut dolorem consequuntur. Vel minus rerum dolorem alias voluptatibus sit laboriosam.", director: "Mila Welch", english: true},
  {title: "The Champagne Friday from the Black Lagoon", year: 1954, plot: "Nemo aperiam non commodi ut. Aliquid officiis quia nesciunt eaque. Iure voluptas omnis atque non facere eius. Molestiae voluptatem consequuntur esse adipisci.", director: "Talitha Klocko", english: true},
  {title: "Codename: Red Mutant", year: 1976, plot: "Minus aperiam inventore ab tenetur repudiandae sint ipsa nam. Repellat velit doloribus consequatur et id provident. Cupiditate vel atque consequatur perspiciatis qui quos commodi.", director: "Kimberely Toy", english: true},
  {title: "Case of the Missing Nuclear Wolves", year: 1923, plot: "Dignissimos ea reiciendis esse magnam omnis odit. Dicta maiores aut consequuntur qui veniam necessitatibus. Sunt explicabo exercitationem et ipsa occaecati consequatur.", director: "Nova Pacocha", english: true},
  {title: "Bloody Cousins: The Catherin Wunsch Story", year: 1920, plot: "Dolore quo nemo aperiam voluptatem autem. Et qui voluptas ducimus dolor quis expedita aut error. Inventore perferendis nesciunt autem molestias reiciendis. Sed voluptatem molestiae earum totam doloremque et. Quibusdam autem molestias ipsam iusto sint.", director: "Tory Boyer", english: true},
  {title: "The Friday from 3942 Leagues", year: 1964, plot: "Tempora magni mollitia repellat repellendus. Ab qui vel non autem amet eaque cupiditate fuga. Dolores consequatur nam omnis ab. Doloremque aspernatur ullam et itaque.", director: "Johnathon Dach", english: true},
  {title: "Ultra Diaries", year: 1963, plot: "Quas officiis voluptatem et commodi earum. Sit aliquam asperiores rem in animi aut nam. Minima et labore in non facilis et. Est debitis magnam hic maxime tenetur saepe et sit.", director: "Rona Morar", english: true},
  {title: "Ultra Pickpocket", year: 1994, plot: "Quam tenetur dolorem aliquam est qui sequi. Quas non fuga ea illo debitis tenetur sed nam. Tenetur velit explicabo culpa non sunt.", director: "Waylon Leannon", english: true},
  {title: "Action Man 2: Son of Action Man", year: 1963, plot: "Omnis dolores nihil magnam sed. Iusto omnis et modi suscipit voluptatum. Ut labore laudantium vel et eaque.", director: "Lance Gerhold", english: true},
  {title: "The Rain from 7730 Leagues", year: 1984, plot: "Aspernatur voluptatem perferendis laboriosam provident. Fugit unde dicta corrupti et voluptatem aut in iure. Voluptatem provident veritatis beatae molestias. Quia quo a alias quia. Beatae ipsum corporis aspernatur et et natus iste.", director: "Valene Kulas", english: true},
  {title: "Nuclear Clash: The Zella Konopelski Story", year: 1980, plot: "Nobis odio velit reiciendis quod enim. Ut sed impedit enim dolorum voluptas. Impedit consequatur quia et ea laudantium sapiente similique. Ea velit excepturi quas eos odio tenetur reprehenderit. Fugiat repellendus quasi autem aut placeat doloremque ipsam.", director: "Meda Ratke", english: true},
  {title: "The Brains from Across the Ocean", year: 1929, plot: "Culpa consectetur repellendus eos numquam nam minus ex distinctio. Ut in earum numquam at porro perspiciatis assumenda. Cum repellendus excepturi odio omnis. Necessitatibus tempora culpa ratione pariatur nam voluptatum placeat tempore.", director: "Jonna Hoeger", english: true},
  {title: "The Forbidden Wolf from Across the Ocean", year: 1930, plot: "Voluptas quasi culpa suscipit nemo. Quis alias quod dolor qui repellendus eos voluptatibus dolores. Nam ut in voluptatem voluptas. Dolorem iusto corrupti mollitia quod quidem. Qui occaecati non facere recusandae totam.", director: "Lai Friesen", english: true},
  {title: "Planet of the Ninja", year: 2014, plot: "Id quia accusamus provident et sint. Eaque iure vitae pariatur est consequuntur deserunt. Ab voluptas minus quia possimus deleniti quo officiis. Corrupti veniam distinctio temporibus eaque ea consequatur quidem.", director: "Graham Yost", english: true},
  {title: "The Monster Who Fell to Earth", year: 2011, plot: "Tempora ab eum earum voluptas ratione culpa itaque labore. Sed consequatur inventore non quo laborum ratione voluptatum. Ratione nam vel esse repudiandae consequatur soluta et. Molestias perspiciatis blanditiis harum voluptatem in ea mollitia nesciunt.", director: "Corliss Pagac", english: true},
  {title: "The Forbidden Blow with a Thousand Faces", year: 1950, plot: "Corrupti sed qui reiciendis unde nam nobis. Aspernatur voluptatem qui iusto quam. Quas esse omnis quia autem. Quasi sit repellat rem incidunt. Similique sed perferendis aut dolorem nihil aut.", director: "Shakita Bosco", english: true}
])
Actor.create!([
  {first_name: "Monique", last_name: "Nader", known_for: "The Yellow Rose of Northern Ireland", gender: "male", age: 64, movie_id: 2},
  {first_name: "Marisol", last_name: "Heller", known_for: "The Cat from Mars", gender: "male", age: 86, movie_id: 1},
  {first_name: "Alvera", last_name: "Mosciski", known_for: "Christmas on Adela Viaduct", gender: "male", age: 78, movie_id: 2},
  {first_name: "Leonor", last_name: "Gulgowski", known_for: "When Joellen Met Brett", gender: "male", age: 28, movie_id: 1},
  {first_name: "Dallas", last_name: "Quigley", known_for: "The Tears from Mars", gender: "female", age: 55, movie_id: 1},
  {first_name: "Federico", last_name: "Braun", known_for: "Champagne Wolves", gender: "male", age: 52, movie_id: 9},
  {first_name: "Layne", last_name: "Rath", known_for: "Red Thief: The Wilfred Wuckert Story", gender: "male", age: 49, movie_id: 3},
  {first_name: "Derick", last_name: "Bednar", known_for: "Christmas on Birgit Parkway", gender: "male", age: 22, movie_id: 10},
  {first_name: "Leeann", last_name: "Jerde", known_for: "Blonde Monster 2: Son of Blonde Monster", gender: "male", age: 20, movie_id: 3},
  {first_name: "Allena", last_name: "Hyatt", known_for: "Planet of the Tokyo Jungle", gender: "female", age: 18, movie_id: 4},
  {first_name: "Nancee", last_name: "Gleason", known_for: "Legend of Tokyo Mutant", gender: "male", age: 27, movie_id: 10},
  {first_name: "Monte", last_name: "Renner", known_for: "Flying Fly", gender: "female", age: 33, movie_id: 10},
  {first_name: "Zoe", last_name: "Adams", known_for: "Christmas on Kami Terrace", gender: "male", age: 78, movie_id: 7},
  {first_name: "Nelda", last_name: "Runolfsdottir", known_for: "The Black Rose of Scotland", gender: "male", age: 51, movie_id: 6},
  {first_name: "Magan", last_name: "Murazik", known_for: "Journey of the Thief", gender: "male", age: 65, movie_id: 4},
  {first_name: "Misha", last_name: "Kilback", known_for: "1186 A.D.", gender: "male", age: 56, movie_id: 6},
  {first_name: "Alverta", last_name: "Gulgowski", known_for: "Dr. Wolf", gender: "female", age: 74, movie_id: 8},
  {first_name: "Heriberto", last_name: "Hahn", known_for: "Hard Boiled Witch", gender: "female", age: 29, movie_id: 6},
  {first_name: "Bambi", last_name: "Zieme", known_for: "Tokyo Journals", gender: "female", age: 57, movie_id: 4},
  {first_name: "Toshiko", last_name: "Brakus", known_for: "War of the Bloody Clash", gender: "female", age: 58, movie_id: 6}
])
Genre.create!([
  {name: "thriller"},
  {name: "drama"},
  {name: "action"},
  {name: "documentary"},
  {name: "comedy"},
  {name: "rom-com"},
  {name: "mystery"},
  {name: "horror"},
  {name: "adventure"},
  {name: "sci-fi"}
])
MovieGenre.create!([
  {genre_id: 2, movie_id: 1},
  {genre_id: 2, movie_id: 2},
  {genre_id: 2, movie_id: 3},
  {genre_id: 2, movie_id: 7},
  {genre_id: 1, movie_id: 7},
  {genre_id: 1, movie_id: 8},
  {genre_id: 2, movie_id: 13},
  {genre_id: 10, movie_id: 6},
  {genre_id: 3, movie_id: 4},
  {genre_id: 3, movie_id: 8},
  {genre_id: 4, movie_id: 11},
  {genre_id: 4, movie_id: 12},
  {genre_id: 6, movie_id: 9},
  {genre_id: 7, movie_id: 5},
  {genre_id: 7, movie_id: 7},
  {genre_id: 7, movie_id: 13},
  {genre_id: 8, movie_id: 5},
  {genre_id: 8, movie_id: 10},
  {genre_id: 9, movie_id: 4},
  {genre_id: 3, movie_id: 17},
  {genre_id: 6, movie_id: 17},
  {genre_id: 5, movie_id: 15},
  {genre_id: 8, movie_id: 16},
  {genre_id: 2, movie_id: 16},
  {genre_id: 7, movie_id: 14}
])
User.create!([
  {name: "Abi", email: "crabigail@gmail.com", password_digest: "$2a$12$yE5ZGqW0J7A0sphP6ZV1ouzJfV7zWrARcriYJ4msh9uj3dyg18xH6", admin: true},
  {name: "Carl", email: "carlh@gmail.com", password_digest: "$2a$12$4UW43/e29T.oDndp2512ouRP92IQYap/buKIN1QvNYnqmp85V0JHK", admin: false}
])
